export { default as useDebounce } from '@/hooks/useDebounce';
export { default as useForm } from '@/hooks/useForm';
export { default as useAuth } from '@/hooks/useAuth';
export { default as useInfiniteMovies } from '@/hooks/useInfiniteMovies';
export { default as useCurrentUser } from '@/hooks/useCurrentUser';
export { default as useFavoriteMovies } from '@/hooks/useFavoriteMovies';
export { default as useToggleFavorite } from '@/hooks/useToggleFavorite';
export { default as useAuthToast } from '@/hooks/useAuthToast';
export { default as useInfiniteScroll } from '@/hooks/useInfiniteScroll';
